### ISSUE TITLE
没有exe文件,没有requests 模块

### ISSUE THREAD

**Issue by Shutong9527** [dyc2424748461/BookImageDownload#1]
没有exe文件,没有requests 模块
用不了

**Comment by Shutong9527** [comment]
userId_and_defid.exe?

**Comment by dyc2424748461** [comment]
@Shutong9527 
1. **exe**文件已上传在[此](https://github.com/dyc2424748461/BookImageDownload/files/10119475/userId_and_defid.changed_for_sort.exe.zip),
2. requests模块请自行安装。
